import type { Product, Order } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Noir de Nuit",
    brand: "Maison Élégance",
    price: 285,
    image: "/luxury-black-perfume-bottle-with-gold-accents.jpg",
    description:
      "An intoxicating blend of midnight florals and exotic spices, crafted for those who dare to embrace the darkness.",
    category: "oriental",
    gender: "unisex",
    size: "100ml",
    stock: 24,
    topNotes: ["Bergamot", "Saffron", "Black Pepper"],
    middleNotes: ["Rose", "Jasmine", "Patchouli"],
    baseNotes: ["Oud", "Amber", "Vanilla"],
    rating: 4.8,
    reviews: 127,
  },
  {
    id: "2",
    name: "Lumière du Matin",
    brand: "Parfums Aurore",
    price: 195,
    image: "/elegant-white-perfume-bottle-morning-light.jpg",
    description:
      "A fresh and luminous fragrance that captures the essence of dawn, with delicate citrus and soft florals.",
    category: "fresh",
    gender: "women",
    size: "75ml",
    stock: 18,
    topNotes: ["Lemon", "Neroli", "Green Tea"],
    middleNotes: ["Lily of the Valley", "Peony", "White Rose"],
    baseNotes: ["Musk", "Cedar", "Sandalwood"],
    rating: 4.9,
    reviews: 203,
  },
  {
    id: "3",
    name: "Ébène Mystique",
    brand: "Atelier des Rêves",
    price: 320,
    image: "/dark-wooden-perfume-bottle-mystical.jpg",
    description:
      "A sophisticated woody composition with smoky undertones, evoking ancient forests and timeless elegance.",
    category: "woody",
    gender: "men",
    size: "100ml",
    stock: 12,
    topNotes: ["Cardamom", "Grapefruit", "Pink Pepper"],
    middleNotes: ["Vetiver", "Cypress", "Ebony Wood"],
    baseNotes: ["Leather", "Tobacco", "Incense"],
    rating: 4.7,
    reviews: 89,
  },
  {
    id: "4",
    name: "Rose Impériale",
    brand: "Maison Élégance",
    price: 265,
    image: "/pink-gold-perfume-bottle-rose-imperial.jpg",
    description:
      "The ultimate tribute to the queen of flowers, a sumptuous rose absolute enhanced with precious ingredients.",
    category: "floral",
    gender: "women",
    size: "50ml",
    stock: 31,
    topNotes: ["Turkish Rose", "Litchi", "Mandarin"],
    middleNotes: ["Bulgarian Rose", "Iris", "Magnolia"],
    baseNotes: ["Ambergris", "Cashmere Wood", "White Musk"],
    rating: 5.0,
    reviews: 156,
  },
  {
    id: "5",
    name: "Vétiver Sauvage",
    brand: "Essences Naturelles",
    price: 175,
    image: "/green-glass-perfume-bottle-vetiver.jpg",
    description: "A vibrant and earthy vetiver fragrance, blending wild grasses with fresh citrus and aromatic herbs.",
    category: "fresh",
    gender: "unisex",
    size: "100ml",
    stock: 45,
    topNotes: ["Grapefruit", "Basil", "Ginger"],
    middleNotes: ["Vetiver", "Geranium", "Clary Sage"],
    baseNotes: ["Oakmoss", "Cedar", "Tonka Bean"],
    rating: 4.6,
    reviews: 92,
  },
  {
    id: "6",
    name: "Ambre Doré",
    brand: "Parfums Aurore",
    price: 295,
    image: "/golden-amber-perfume-bottle-luxurious.jpg",
    description: "A warm and enveloping amber fragrance with spicy accents and a honeyed sweetness.",
    category: "oriental",
    gender: "unisex",
    size: "75ml",
    stock: 22,
    topNotes: ["Cinnamon", "Orange Blossom", "Artemisia"],
    middleNotes: ["Honey", "Labdanum", "Jasmine"],
    baseNotes: ["Amber", "Benzoin", "Vanilla"],
    rating: 4.9,
    reviews: 174,
  },
  {
    id: "7",
    name: "Citrus Élite",
    brand: "Atelier des Rêves",
    price: 155,
    image: "/yellow-citrus-perfume-bottle-fresh.jpg",
    description: "A sparkling citrus symphony perfect for the modern sophisticate, bright yet surprisingly complex.",
    category: "citrus",
    gender: "unisex",
    size: "100ml",
    stock: 38,
    topNotes: ["Bergamot", "Yuzu", "Blood Orange"],
    middleNotes: ["Neroli", "Petit Grain", "Ginger Lily"],
    baseNotes: ["White Musk", "Vetiver", "Ambroxan"],
    rating: 4.5,
    reviews: 68,
  },
  {
    id: "8",
    name: "Orchidée Noire",
    brand: "Maison Élégance",
    price: 340,
    image: "/black-purple-perfume-bottle-orchid.jpg",
    description: "An opulent and seductive floral masterpiece featuring rare black orchid and rich dark chocolate.",
    category: "floral",
    gender: "women",
    size: "50ml",
    stock: 15,
    topNotes: ["Black Truffle", "Ylang-Ylang", "Black Currant"],
    middleNotes: ["Black Orchid", "Lotus", "Spiced Rum"],
    baseNotes: ["Dark Chocolate", "Patchouli", "Incense"],
    rating: 4.8,
    reviews: 142,
  },
]

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    date: "2025-01-01",
    customer: {
      name: "Sophie Laurent",
      email: "sophie.laurent@example.com",
      phone: "+33 1 23 45 67 89",
      address: "12 Rue de Rivoli, 75001 Paris, France",
    },
    items: [
      { ...mockProducts[0], quantity: 1 },
      { ...mockProducts[3], quantity: 2 },
    ],
    total: 815,
    status: "delivered",
  },
  {
    id: "ORD-002",
    date: "2025-01-02",
    customer: {
      name: "Alexander Chen",
      email: "alex.chen@example.com",
      phone: "+1 555 123 4567",
      address: "456 Park Avenue, New York, NY 10022, USA",
    },
    items: [{ ...mockProducts[2], quantity: 1 }],
    total: 320,
    status: "shipped",
  },
]
